name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint || echo "Linting issues found"
      
    - name: Test
      run: npm test -- --coverage
      
    # Only run if CODECOV_TOKEN secret exists
    - name: Check for Codecov token
      id: check_codecov
      run: |
        if [ "${{ secrets.CODECOV_TOKEN }}" != "" ]; then
          echo "has_token=true" >> $GITHUB_OUTPUT
        else
          echo "has_token=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: steps.check_codecov.outputs.has_token == 'true'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        fail_ci_if_error: false
