name: Deploy

on:
  push:
    branches: [ main ]
    
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Deploy to staging
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
      run: |
        echo "Deploying to staging server..."
        # Add your deployment script here
        # Example: rsync -avz --delete dist/ user@$STAGING_SERVER:/path/to/deployment/
        
    - name: Notify deployment status
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Deployment Status
        SLACK_MESSAGE: 'Deployment to staging ${{ job.status }}'
